import { AxiosResponse } from 'axios'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { Tabs } from '../components'
import { fetchCategories } from '../https'
import { ICategory, ICollectionResponse } from '../types'

interface IPropTypes {
  categories: {
    items: ICategory[]
  }
}

const Home: NextPage<IPropTypes> = ({ categories }) => {
  console.log(categories, 'categories')
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs categories={categories.items} />

      <h1 className='text-primary text-3xl font-bold underline'>
        Welcome to Headless Blog
      </h1>



    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCategories()
  return {
    props: {
      categories: {
        items: categories?.data
      }
    }
  }
}

export default Home
